### ISSUE TITLE
List are not aligned in the menu

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/docs#80]
Lists are not aligned correctly in the menu but also on any page.

### Before:

<img width="298" alt="Screen Shot 2019-09-19 at 15 38 43" src="https://user-images.githubusercontent.com/5823445/65227873-9ef0cc80-daf3-11e9-8c12-6588e6df8ad7.png">

### After:

<img width="298" alt="Screen Shot 2019-09-19 at 15 38 53" src="https://user-images.githubusercontent.com/5823445/65227859-98faeb80-daf3-11e9-9f69-8c6073b7f34c.png">

**Comment by NicolasMahe** [comment]
This has been fixed
